language: csharp
mono: latest
dotnet: 3.1.302
before_install:
 - sudo apt-get update
install:
 - dotnet restore
script:
 - msbuild /p:Configuration=Debug Library/MintPlayer.Xamarin.Forms.SortableListView/MintPlayer.Xamarin.Forms.SortableListView.csproj
sudo: required
